$(document).ready(function(){
  $("#pageone0").click(function(){
    $("#pageone-1").fadeIn("slow");
  });
});
$(document).ready(function(){
  $(".pageone-1-btn1").click(function(){
  	$("#pageone-1").fadeToggle("slow");
});
});
$(document).ready(function(){
  $("#pageone1").click(function(){
    $("#pageone-2").fadeIn("slow");
  });
});
$(document).ready(function(){
  $(".pageone-2-btn1").click(function(){
  	$("#pageone-2").fadeToggle("slow");
});
});
$(document).ready(function(){
  $("#pageone2").click(function(){
    $("#pageone-4").fadeIn("slow");
  });
});
$(document).ready(function(){
  $(".pageone-3-btn1").click(function(){
  	$("#pageone-4").fadeToggle("slow");
});
});